#!/bin/bash

#   WARNING: DO NOT USE RUN SCRIPT FROM ROOT [/] OR HOME [/home] DIRECTORY
#   USE A SEPRATE LOCATION LIKE [BAKPATH]
BAKPATH="/mnt/Data/Backup"

#   Home Folders and Files

echo "Checking for old backup ...."
sleep 1
if [ -d "$BAKPATH" ]; then
rm -Rf $BAKPATH
echo 'Old backup removed. Creating new ....'
sleep 1
mkdir $BAKPATH
#   List of files/folders of /home folders which needs to backup
cp -Rf $HOME $BAKPATH
echo 'New backup completed.'
else
echo 'No old backup found. Creating first time ....'
mkdir $BAKPATH
sleep 1
#   List of files/folders of /home folders which needs to backup
cp -Rf $HOME $BAKPATH
echo 'Backup completed.'
fi
