#!/bin/bash

#   WARNING: DO NOT USE RUN SCRIPT FROM ROOT [/] OR HOME [/home] DIRECTORY
#   USE A SEPRATE LOCATION LIKE [BAKPATH] & [BAKFOL]

BAKPATH="/mnt/Data"
BAKFOL="BakHome"

#   Home Folders and Files
echo "==============================================================================="
echo "Checking for old backup ...."
echo "==============================================================================="
sleep 1

cd $BAKPATH

if [ -d "$BAKFOL" ]; then
rm -Rf $BAKFOL
echo "==============================================================================="
echo 'Old backup removed. Creating new ....'
echo "==============================================================================="
sleep 1
mkdir $BAKFOL

#   List of files/folders of /home folders which needs to backup
cd $HOME
cp -Rf $HOME $BAKPATH/$BAKFOL
echo "==============================================================================="
echo 'Backup of '/home' directory has completed.'
echo "==============================================================================="
#   Running pkgs backup script
sh .bakpkgs.sh

else
echo "==============================================================================="
echo 'No old backup found. Creating ....'
echo "==============================================================================="
mkdir $BAKFOL
sleep 1

#   List of files/folders of /home folders which needs to backup
cd $HOME
cp -Rf $HOME $BAKPATH/$BAKFOL
echo "==============================================================================="
echo 'Backup of '/home' directory has completed.'
echo "==============================================================================="
#   Running pkgs backup script
sh .bakpkgs.sh
fi
