#!/bin/bash

#   WARNING: DO NOT USE RUN SCRIPT FROM ROOT [/] OR HOME [/home] DIRECTORY
#   USE A SEPRATE LOCATION LIKE [BAKPATH] & [BakHome]

BAKPATH="/mnt/Data"
BAKFOL="BakHome"

#   Home Folders and Files

echo "Checking for old backup ...."
sleep 1

cd $BAKPATH

if [ -d "$BAKFOL" ]; then
rm -Rf $BAKFOL
echo 'Old backup removed. Creating new ....'
sleep 1
mkdir $BAKFOL

#   List of files/folders of /home folders which needs to backup
cd $HOME
cp -Rf $HOME $BAKPATH/$BAKFOL
echo 'Backup of /home has completed.'
#   Running pkgs backup script
sh .bakpkgs.sh

else

echo 'No old backup found. Creating first time ....'
mkdir $BAKFOL
sleep 1

#   List of files/folders of /home folders which needs to backup
cd $HOME
cp -Rf $HOME $BAKPATH/$BAKFOL
echo 'Backup of /home has completed.'
#   Running pkgs backup script
sh .bakpkgs.sh
fi
