#!/bin/bash
# Added by AKM
sed -e 's|ZSH_THEME="random"|ZSH_THEME="bira"|g' -i $HOME/.zshrc
#echo 'export LC_CTYPE=en_US.UTF-8
#export LC_ALL=en_US.UTF-8' | tee -a $HOME/.zshrc

echo "################################################################"
echo "###################    T H E   E N D      ######################"
echo "################################################################"
